export const orders = [
  {
    name: 'Liam Johnson',
    company: 'Peak Milk',
    email: 'liam.johnson@peakmilk.com',
    phone: '09023456789',
    product: 'Lagos - Abuja',
    status: 'fulfilled',
    date: '2023-06-23',
    amount: 1500000.0,
  },
  {
    name: 'Grace Williams',
    company: 'Dano Milk',
    email: 'grace.williams@danomilk.com',
    phone: '09034567890',
    product: 'Ibadan - Lagos',
    status: 'pending',
    date: '2023-06-18',
    amount: 750000.0,
  },
  {
    name: 'Michael Brown',
    company: 'Nestle',
    email: 'michael.brown@nestle.com',
    phone: '09045678901',
    product: 'Kano - Jos',
    status: 'fulfilled',
    date: '2023-07-10',
    amount: 1200000.0,
  },
  {
    name: 'Emily Davis',
    company: 'Coca-Cola',
    email: 'emily.davis@coca-cola.com',
    phone: '09056789012',
    product: 'Abuja - Kaduna',
    status: 'in-progress',
    date: '2023-08-05',
    amount: 980000.0,
  },
  {
    name: 'James Smith',
    company: 'Pepsi',
    email: 'james.smith@pepsi.com',
    phone: '09067890123',
    product: 'Lagos - Port Harcourt',
    status: 'canceled',
    date: '2023-09-15',
    amount: 1350000.0,
  },
  {
    name: 'Sophia Martinez',
    company: 'FrieslandCampina',
    email: 'sophia.martinez@friesland.com',
    phone: '09078901234',
    product: 'Jos - Abuja',
    status: 'fulfilled',
    date: '2023-10-02',
    amount: 890000.0,
  },
  {
    name: 'Benjamin Lee',
    company: 'Chi Limited',
    email: 'benjamin.lee@chiltd.com',
    phone: '09089012345',
    product: 'Ibadan - Abuja',
    status: 'in-progress',
    date: '2023-07-21',
    amount: 1125000.0,
  },
  {
    name: 'Isabella Johnson',
    company: 'Dangote',
    email: 'isabella.johnson@dangote.com',
    phone: '09090123456',
    product: 'Lagos - Kano',
    status: 'fulfilled',
    date: '2023-05-30',
    amount: 1450000.0,
  },
  {
    name: 'Lucas Garcia',
    company: 'Unilever',
    email: 'lucas.garcia@unilever.com',
    phone: '09101234567',
    product: 'Ibadan - Ilorin',
    status: 'pending',
    date: '2023-04-12',
    amount: 780000.0,
  },
  {
    name: 'Mia Wilson',
    company: 'Cadbury',
    email: 'mia.wilson@cadbury.com',
    phone: '09112345678',
    product: 'Abuja - Benin',
    status: 'fulfilled',
    date: '2023-08-28',
    amount: 950000.0,
  },
  {
    name: 'Noah Moore',
    company: 'Nestle',
    email: 'noah.moore@nestle.com',
    phone: '09123456789',
    product: 'Kano - Lagos',
    status: 'fulfilled',
    date: '2023-03-07',
    amount: 1420000.0,
  },
  {
    name: 'Amelia White',
    company: 'Dangote',
    email: 'amelia.white@dangote.com',
    phone: '09134567890',
    product: 'Abuja - Enugu',
    status: 'in-progress',
    date: '2023-07-12',
    amount: 1300000.0,
  },
  {
    name: 'Oliver Martinez',
    company: 'Coca-Cola',
    email: 'oliver.martinez@coca-cola.com',
    phone: '09145678901',
    product: 'Benin - Lagos',
    status: 'pending',
    date: '2023-06-01',
    amount: 820000.0,
  },
  {
    name: 'Elijah Clark',
    company: 'Pepsi',
    email: 'elijah.clark@pepsi.com',
    phone: '09156789012',
    product: 'Abuja - Kano',
    status: 'fulfilled',
    date: '2023-05-16',
    amount: 1320000.0,
  },
  {
    name: 'Charlotte Hall',
    company: 'Chi Limited',
    email: 'charlotte.hall@chiltd.com',
    phone: '09167890123',
    product: 'Kano - Port Harcourt',
    status: 'canceled',
    date: '2023-09-05',
    amount: 980000.0,
  },
  {
    name: 'William Young',
    company: 'FrieslandCampina',
    email: 'william.young@friesland.com',
    phone: '09178901234',
    product: 'Lagos - Enugu',
    status: 'fulfilled',
    date: '2023-02-28',
    amount: 1015000.0,
  },
  {
    name: 'Evelyn Hernandez',
    company: 'Unilever',
    email: 'evelyn.hernandez@unilever.com',
    phone: '09189012345',
    product: 'Ibadan - Jos',
    status: 'in-progress',
    date: '2023-03-19',
    amount: 1190000.0,
  },
  {
    name: 'Logan King',
    company: 'Nestle',
    email: 'logan.king@nestle.com',
    phone: '09190123456',
    product: 'Kaduna - Lagos',
    status: 'pending',
    date: '2023-04-24',
    amount: 1450000.0,
  },
  {
    name: 'Ava Wright',
    company: 'Peak Milk',
    email: 'ava.wright@peakmilk.com',
    phone: '09101234567',
    product: 'Jos - Lagos',
    status: 'fulfilled',
    date: '2023-06-15',
    amount: 920000.0,
  },
  {
    name: 'Daniel Scott',
    company: 'Dano Milk',
    email: 'daniel.scott@danomilk.com',
    phone: '09112345678',
    product: 'Lagos - Abuja',
    status: 'fulfilled',
    date: '2023-07-30',
    amount: 880000.0,
  },
  {
    name: 'Sophia Green',
    company: 'FrieslandCampina',
    email: 'sophia.green@friesland.com',
    phone: '09123456789',
    product: 'Ibadan - Enugu',
    status: 'fulfilled',
    date: '2023-05-22',
    amount: 1045000.0,
  },
  {
    name: 'Sebastian Baker',
    company: 'Pepsi',
    email: 'sebastian.baker@pepsi.com',
    phone: '09134567890',
    product: 'Kano - Jos',
    status: 'canceled',
    date: '2023-08-18',
    amount: 960000.0,
  },
  {
    name: 'Ella Evans',
    company: 'Cadbury',
    email: 'ella.evans@cadbury.com',
    phone: '09145678901',
    product: 'Lagos - Kaduna',
    status: 'pending',
    date: '2023-04-02',
    amount: 850000.0,
  },
  {
    name: 'Henry Nelson',
    company: 'Coca-Cola',
    email: 'henry.nelson@coca-cola.com',
    phone: '09156789012',
    product: 'Benin - Lagos',
    status: 'fulfilled',
    date: '2023-03-29',
    amount: 1250000.0,
  },
]

export const events = [
  {
    id: 1,
    title: 'Lagos - Abuja',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-11-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 2,
    title: 'Abuja - Jos',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-14-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 3,
    title: 'Lagos - Portharcourt',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-21-10',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 11,
    title: 'Lagos - Abuja',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-11-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 21,
    title: 'Abuja - Jos',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-14-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 31,
    title: 'Lagos - Portharcourt',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-21-10',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 61,
    title: 'Lagos - Abuja',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-11-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 41,
    title: 'Abuja - Jos',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-14-11',
    startTime: '10:00',
    endTime: '11:00',
  },
  {
    id: 51,
    title: 'Lagos - Portharcourt',
    class:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque ad qui laboriosam eum, eveniet quidem hic reiciendis ex tenetur, libero possimus quisquam nobis?',
    date: '2024-21-10',
    startTime: '10:00',
    endTime: '11:00',
  },
]

export const users = [
  {
    name: 'Obawolu Idowu',
    email: 'O.Idowu@carnationregistrars.com',
    phone: '09012345678',
    role: 'admin',
    position: 'HR',
    userId: 3465278,
    image: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
  },
  {
    name: 'Adebayo Oluwaseun',
    email: 'A.Oluwaseun@carnationregistrars.com',
    phone: '09023456789',
    role: 'user',
    position: 'Finance',
    userId: 3465279,
    image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
  },
  {
    name: 'Adeyemi Tobi',
    email: 'A.Tobi@carnationregistrars.com',
    phone: '09034567890',
    role: 'admin',
    position: 'HR',
    userId: 3465280,
    image: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg',
  },
  {
    name: 'Oluwadamilola Femi',
    email: 'O.Femi@carnationregistrars.com',
    phone: '09045678901',
    role: 'supervisor',
    position: 'Operations',
    userId: 3465281,
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    name: 'Okonkwo Chidera',
    email: 'O.Chidera@carnationregistrars.com',
    phone: '09056789012',
    role: 'user',
    position: 'IT',
    userId: 3465282,
    image: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'Adefemi Bimbo',
    email: 'A.Bimbo@carnationregistrars.com',
    phone: '09067890123',
    role: 'supervisor',
    position: 'Admin',
    userId: 3465283,
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
  },
  {
    name: 'Ogunleye Samuel',
    email: 'O.Samuel@carnationregistrars.com',
    phone: '09078901234',
    role: 'supervisor',
    position: 'HR',
    userId: 3465284,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
  },
  {
    name: 'Akinwale Segun',
    email: 'A.Segun@carnationregistrars.com',
    phone: '09089012345',
    role: 'user',
    position: 'Finance',
    userId: 3465285,
    image: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg',
  },
  {
    name: 'Ifeoma Nnenna',
    email: 'I.Nnenna@carnationregistrars.com',
    phone: '09090123456',
    role: 'supervisor',
    position: 'Operations',
    userId: 3465286,
    image: 'https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg',
  },
  {
    name: 'Ogundipe Sola',
    email: 'O.Sola@carnationregistrars.com',
    phone: '09101234567',
    role: 'supervisor',
    position: 'IT',
    userId: 3465287,
    image: 'https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg',
  },
  {
    name: 'Osinachi Ugo',
    email: 'O.Ugo@carnationregistrars.com',
    phone: '09112345678',
    role: 'user',
    position: 'Finance',
    userId: 3465288,
    image: 'https://images.pexels.com/photos/4585424/pexels-photo-4585424.jpeg',
  },
  {
    name: 'Eze Mary',
    email: 'E.Mary@carnationregistrars.com',
    phone: '09123456789',
    role: 'user',
    position: 'HR',
    userId: 3465289,
    image: 'https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg',
  },
  {
    name: 'Ajayi Bolu',
    email: 'A.Bolu@carnationregistrars.com',
    phone: '09134567890',
    role: 'user',
    position: 'Admin',
    userId: 3465290,
    image: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg',
  },
  {
    name: 'Amadi Chinelo',
    email: 'A.Chinelo@carnationregistrars.com',
    phone: '09145678901',
    role: 'supervisor',
    position: 'Operations',
    userId: 3465291,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
  },
  {
    name: 'Ojo Kehinde',
    email: 'O.Kehinde@carnationregistrars.com',
    phone: '09156789012',
    role: 'admin',
    position: 'IT',
    userId: 3465292,
    image: 'https://images.pexels.com/photos/428339/pexels-photo-428339.jpeg',
  },
]

export const invoiceColumns = [
  {
    header: 'Customer',
    accessor: 'customer',
  },
  {
    header: 'Product',
    accessor: 'product',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'Status',
    accessor: 'status',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'Date',
    accessor: 'date',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'Amount',
    accessor: 'amount',
    className: 'text-right',
  },
]

export const usersColumns = [
  {
    header: 'User',
    accessor: 'user',
  },
  {
    header: 'Phone Number',
    accessor: 'phone',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'Role',
    accessor: 'role',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'Position',
    accessor: 'position',
    className: 'hidden sm:table-cell',
  },
  {
    header: 'User Id',
    accessor: 'userId',
    className: 'text-right',
  },
]

export const singleOrder = [
  {
    name: 'Liam Johnson',
    company: 'Peak Milk',
    email: 'liam.johnson@peakmilk.com',
    phone: '09023456789',
    product: 'Lagos - Abuja',
    status: 'fulfilled',
    date: '2023-06-23',
    description: 'Carrying 30 packs of loaded peak milk to abuja only',
    amount: 1500000.0,
  },
]

export const statuses = [
  {
    id: 'pending',
    label: 'Pending',
  },
  {
    id: 'inProgress',
    label: 'In Progress',
  },
  {
    id: 'fulfilled',
    label: 'Fulfilled',
  },
  {
    id: 'cancelled',
    label: 'Cancelled',
  },
]
